### PR TITLE
Issue 48 disable reconnecting while wiping

### PR DESCRIPTION
**Pull request by szszszsz**
Do not show tray messages during SD card clearing.

### CODE REVIEW

**Comment by szszszsz** [comment]
For now this will remove the effect of the bug, which were multiple messages in tray.
There is still the cause that needs to be fixed.

**Comment by szszszsz** [comment]
Partly fixes issue #48 (only from user perspective)

**Comment by jans23** [comment]
Is the progress bar still be used and, once the entire space is
initialized, finished with a success message? That would be required,
please.

>

**Comment by szszszsz** [comment]
Hi @jans23 
Yes, the progress bar remained intact, as is final success message.
Everything is as it were besides removing (only for time of wiping) all status messages from tray, which were mainly (showed each 5 seconds):
> [ "Nitrokey disconnected" ]  ""
> [ "Nitrokey connected" ]  "Nitrokey Storage"
and adding information for user to reinsert the stick to final message about successful wiping.

**Comment by jans23** [comment]
Since the root cause has been solved in latest NK Storage firmware, please revert this change.

**Pull request merged**
