### PR TITLE
Minor language change and typo

### PR DESCRIPTION
**Pull request by alex-nitrokey**
Hi,

the string is missing the "do" in English and was ambiguous in German.

Kind regards
Alex

### CODE REVIEW

**Comment by oderwat** [comment]
I think the sentences could be made better. Explanation in German (because it makes no sense to talk in english about it :)

Ich würde ja "Wollen Sie sie ändern?" oder "Wollen Sie sie jetzt ändern?" nehmen. Unser schönes "gleich" kann ja auch "jetzt" oder "demnächst" heissen.

**Comment by alex-nitrokey** [comment]
:thinking: da ist was dran... :+1:

**Comment by szszszsz** [comment]
Hi!
Is this one ready to merge?

**Comment by alex-nitrokey** [comment]
Sure. But I don't know about this travis check failure. This should be connected to the translation of english string. You know what you have to do with that? If so, merging is fine :+1:

**Pull request closed without merging**
