### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by LennardBoediger**
Automated (unsinged) builds for nitrokey-app:
https://git.dotplex.com/nitrokey/nitrokey-app/-/pipelines/14938

Build for MacOS is still in work in progress.

### CODE REVIEW

**Comment by daringer** [comment]
uha this is a lot, please squash them together

**Comment by LennardBoediger** [comment]
I disabled the Mac-Build and squashed all commits - Ready to Merge

**Comment by daringer** [comment]
looks good to me, @szszszsz can you merge please?

**Comment by szszszsz** [comment]
Sure. 
@LennardBoediger : as discussed, looking forward for the macOS build!

**Comment by szszszsz** [comment]
@LennardBoediger By the way, let's consider moving away from the Bash scripts, and using Makefiles instead

**Comment by szszszsz** [comment]
Confirmed AppImage and MXE Windows builds are working

**Comment by szszszsz** [comment]
Note: all builds are fast (< 3 minutes) except for the flatpak, which takes 8 minutes to run.

**Pull request closed without merging**
