### PR TITLE
final update of nitrokey_pl.ts

### PR DESCRIPTION
**Pull request by grzegi**
Final update of Polish translation. Ready to go.

### CODE REVIEW

**Comment by grzegi** [comment]
@szszszsz final polish translation is here.

**Comment by szszszsz** [comment]
Hi! Thank you for another big update and sorry for the late reply!

It will be merged on the next release. Personally I have some objections regarding the `Password Safe` name - is `Sejf Haseł` sounding better to you, than `Bank Haseł`?

**Comment by grzegi** [comment]
Good point. Agree with proposal :)

wt., 18 wrz 2018 o 10:35 Szczepan Zalega <notifications@github.com>
napisał(a):

**Comment by szszszsz** [comment]
OK! I will correct it on merge :-)

**Comment by grzegi** [comment]
Thanks a lot! For now translation is complete!

wt., 18 wrz 2018 o 10:40 Szczepan Zalega <notifications@github.com>
napisał(a):

**Comment by szszszsz** [comment]
Maintainers note: fixes #358

**Pull request merged**
