### PR TITLE
nitrokey_pl.ts

### PR DESCRIPTION
**Pull request by grzegi**
polish translation - corrected

### CODE REVIEW

**Comment by grzegi** [comment]
translation corrected, to be included in new build, requires further adjustments.

**Comment by szszszsz** [comment]
Hi @grzegi !

Thank you for the PR! I will merge it and prepare a test build for further adjustments. It should be available tomorrow.

**Comment by szszszsz** [comment]
Released in [v1.3.2-RC1](https://github.com/Nitrokey/nitrokey-app/releases/tag/v1.3.2-RC1).

**Comment by jans23** [comment]
@grzegi Do you plan further updates/reviews or is it a final translation from your point of view?

**Comment by grzegi** [comment]
@jans23  - I am planning at least one more update - tommorow or on Wednesday.

**Pull request merged**
