### PR TITLE
i18n: Add Italian translation.

### PR DESCRIPTION
**Pull request by comio**
Dera All,

I'm providing you the Italian translation as is.
I'm sorry but I have not still reviewed because I haven't my Nitrokey Pro yet (out of stock :sad:) and I cannot navigate into the gui to check the translation quality (the main problem is the italian produces longer sentences w.r.t. english).

Furthermore I haven't Nitrokey Storage and I cannot validate for this use case.

I will propose in the future a new PR with the translation reviewed.

Final note: on my setup I need to include PR #346 in order to see the translated strings.

I hope in your feedback.

Luigi

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi! You have marked one of the commits as WIP - should I wait with merge?

**Comment by comio** [comment]
Wait. I still haven't received the my nitrokey pro :'( and I cannot check and validate the translation.

I will squash the commits into just one at the end.

Ciao

Luigi

**Comment by comio** [comment]
@szszszsz 

Nitrokey Pro is in my hands. Give me this weekend to check again (I already had yesterday).
Side note can you merge also #348 ?

ciao

luigi

**Comment by szszszsz** [comment]
Great!
Sure! Sorry for delay. It should be merged this week.

**Comment by szszszsz** [comment]
Thank you!
I will check it. Do you suspect the source of the bug (for quick start)? 
Just a sanity check - have you run `lupdate` and `lrelease` before tests?

**Comment by comio** [comment]
I haven't... ops

I will do :)

ciao

luigi

**Comment by comio** [comment]
lupdate & lrelease done.

You can merge (after your review).

ciao

luigi

**Comment by szszszsz** [comment]
Thank you once again!

**Pull request merged**
