### PR TITLE
Modernise CMake

### PR DESCRIPTION
**Pull request by SoapGentoo**
* Try to first use system libnitrokey, which
  is important for Linux distros that unbundle
  libraries.
* Use `GNUInstallDirs` module for paths, allows
  changing of directories for users and distros.
* Use `BUILD_SHARED_LIBS`, which is the
  idiomatic way to switch between static
  and shared libraries in CMake.
    https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html
* Do not enable `-Werror` by default. This
  just causes unnecessary issues with new
  compiler releases.
    https://blog.flameeyes.eu/2009/02/future-proof-your-code-dont-use-werror/

### CODE REVIEW

**Comment by szszszsz** [comment]
Hi and sorry for delay!
I really needed the changes with `GNUInstallDirs` and `BUILD_SHARED_LIBS`. Thank you!
Regarding `-Werror`, indeed this probably makes issues during packaging. Have not thought about that (have not read the blog post yet). Added that for CI mainly.
Is the PR work on your side in case of bundled `libnitrokey`? It seems not compiling on the [Travis CI](https://travis-ci.org/Nitrokey/nitrokey-app/builds/304973118?utm_source=github_status&utm_medium=notification).

**Comment by SoapGentoo** [comment]
@szszszsz it actually depends on the libnitrokey PR, but I will fix it to work without

**Comment by szszszsz** [comment]
@SoapGentoo I see! There is no need, I will check the other PR and make local test.

**Comment by SoapGentoo** [comment]
@szszszsz simplified it a bit, and enabled `-Werror` only in Travis. This PR doesn't depend on the libnitrokey one (but please also merge that one, it's important for packaging in distros).

**Comment by szszszsz** [comment]
Hi! Sorry, I was busy with something else last week.
I have tested this with https://github.com/Nitrokey/libnitrokey/pull/80 PR installed on the system. `Pkg-config` is finding the library and gives correct library's linking name and directory flags, but in final `nitrokey-app` binary `libnitrokey` has no absolute path and it is not found. Any ideas how to solve it?
Tested on Ubuntu 17.10, CMake 3.9.1, pkg-config 0.29.1, GCC 7.2.0.

The error flag works as expected.

**Comment by szszszsz** [comment]
After a rethought I rechecked this with removed CMake cache and it worked - sorry for confusion!

**Comment by szszszsz** [comment]
@SoapGentoo Merged, thank you!

**Pull request closed without merging**
